services:
  dns:
    container_name: dns-app
    image: dns-app:1.0
    restart: always
    volumes:
      - dns:/data
    networks:
      - nginx
    command: ping 1.1.1.1
    extra_hosts:
      - "google.com=8.8.8.8"
      - "cloudflare=1.1.1.1"

networks:
  nginx:
    external: true

volumes:
  dns:
    external: true
