services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - nginx:/usr/share/nginx/html/
    networks:
      - nginx
    ports:
      - 80:80
      - 3000:80


volumes:
  nginx:
    external: true

networks:
  nginx:
    external: true
