services:
  alpine:
    container_name: alpine
    image: alpine:latest
    volumes:
      - alpine:/app
    networks:
      - alpine
    restart: always
    command: ["/bin/sh","-c","ping -i 5 1.1.1.1"]
    env_file: "variable.env"

volumes:
  alpine:
    external: true

networks:
  alpine:
    external: true
